"""Filter obfuscation middlewares."""

from .types import FilterMiddleware, FilterMiddlewareChain
from .helpers import leaf_applier, map_to_oid, generate_garbage_filter
from .obfuscation import (
    oid_attribute_filter_obf,
    anr_attribute_filter_obf,
    anr_substring_garbage_filter_obf,
    rand_garbage_filter_obf,
    equality_by_inclusion_filter_obf,
    equality_by_exclusion_filter_obf,
    exact_bitwise_breakout_filter_obf,
    bitwise_decompose_filter_obf,
    rand_add_bool_filter_obf,
    rand_dbl_neg_bool_filter_obf,
    de_morgan_bool_filter_obf,
    rand_bool_reorder_filter_obf,
    rand_case_filter_obf,
    equality_to_approx_match_filter_obf,
    rand_hex_value_filter_obf,
    rand_timestamp_suffix_filter_obf,
    rand_prepend_zeros_filter_obf,
    rand_spacing_filter_obf,
    rand_substring_split_filter_obf,
    equality_to_extensible_filter_obf,
    replace_tautologies_filter_obf,
)

__all__ = [
    "FilterMiddleware",
    "FilterMiddlewareChain",
    "leaf_applier",
    "map_to_oid",
    "generate_garbage_filter",
    "oid_attribute_filter_obf",
    "anr_attribute_filter_obf",
    "anr_substring_garbage_filter_obf",
    "rand_garbage_filter_obf",
    "equality_by_inclusion_filter_obf",
    "equality_by_exclusion_filter_obf",
    "exact_bitwise_breakout_filter_obf",
    "bitwise_decompose_filter_obf",
    "rand_add_bool_filter_obf",
    "rand_dbl_neg_bool_filter_obf",
    "de_morgan_bool_filter_obf",
    "rand_bool_reorder_filter_obf",
    "rand_case_filter_obf",
    "equality_to_approx_match_filter_obf",
    "rand_hex_value_filter_obf",
    "rand_timestamp_suffix_filter_obf",
    "rand_prepend_zeros_filter_obf",
    "rand_spacing_filter_obf",
    "rand_substring_split_filter_obf",
    "equality_to_extensible_filter_obf",
    "replace_tautologies_filter_obf",
]
