"""String manipulation helpers for LDAP obfuscation."""

from .string import (
    generate_garbage_string,
    hex_encode_char,
    randomly_hex_encode_string,
    randomly_change_case_string,
    randomly_prepend_zeros_oid,
    randomly_hex_encode_dn_string,
    replace_timestamp,
    prepend_zeros_to_sid,
    prepend_zeros_to_number,
    add_anr_spacing,
    add_dn_spacing,
    add_sid_spacing,
    get_next_string,
    get_previous_string,
    get_next_sid,
    get_previous_sid,
    split_slice,
    CHAR_ORDERING,
)

__all__ = [
    "generate_garbage_string",
    "hex_encode_char",
    "randomly_hex_encode_string",
    "randomly_change_case_string",
    "randomly_prepend_zeros_oid",
    "randomly_hex_encode_dn_string",
    "replace_timestamp",
    "prepend_zeros_to_sid",
    "prepend_zeros_to_number",
    "add_anr_spacing",
    "add_dn_spacing",
    "add_sid_spacing",
    "get_next_string",
    "get_previous_string",
    "get_next_sid",
    "get_previous_sid",
    "split_slice",
    "CHAR_ORDERING",
]
